# Generated by Django 3.0.7 on 2020-06-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.IntegerField()),
                ('stations', models.IntegerField()),
            ],
        ),
    ]
