# Generated by Django 2.1.2 on 2020-06-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='Maps',
        ),
    ]
