# Generated by Django 2.1.2 on 2020-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0002_auto_20200616_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.CharField(max_length=3)),
                ('right', models.CharField(max_length=3)),
                ('left', models.CharField(max_length=3)),
                ('straight', models.CharField(max_length=3)),
                ('ldist', models.IntegerField()),
                ('rdist', models.IntegerField()),
                ('sdist', models.IntegerField()),
            ],
        ),
    ]
