# Generated by Django 2.1.2 on 2020-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0003_node_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node_details',
            name='current',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='ldist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='left',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='rdist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='right',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='sdist',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node_details',
            name='straight',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
