# Generated by Django 2.1.2 on 2020-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0004_auto_20200619_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('dest', models.IntegerField()),
            ],
        ),
    ]
