# Generated by Django 2.1.2 on 2020-06-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0005_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='dest',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='short',
            name='start',
            field=models.CharField(max_length=3),
        ),
    ]
