# Generated by Django 2.1.2 on 2020-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0006_auto_20200619_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='dest',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='start',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
