# Generated by Django 3.0.7 on 2020-07-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map_generation', '0007_auto_20200619_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regagv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agvsname', models.CharField(blank=True, max_length=10, null=True)),
                ('agvsid', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
